### ISSUE TITLE
Bug: InstanaAgent/Agent CRD Naming Issue Causes kubectl Commands to Fail

### ISSUE THREAD

**Issue by O7Oghany** [instana/instana-agent-operator#227]
Hello,

I discovered a bug when trying to list or delete `InstanaAgent` objects using `kubectl`. The following commands return no objects:

```shell
kubectl get InstanaAgent -A
kubectl get InstanaAgents -A
kubectl get agent -A
kubectl get agents -A
```

The only commands that work are using the full API group or the short name.

```shell
kubectl get instanaagent.instana.io
kubectl get ia -A

```
---

## Investigation and Findings

After inspecting the CRD, I found that there is a mismatch between the `singular`, `plural`, and `kind` names in the CRD definition:

```yaml
spec:
  conversion:
    strategy: None
  group: instana.io
  names:
    categories:
    - monitoring
    - openshift-optional
    kind: InstanaAgent
    listKind: InstanaAgentList
    plural: agents
    shortNames:
    - ia
    singular: agent
```
This mismatch is likely causing `kubectl` to fail when using commands like `kubectl get instanaagent`.

---

## Resolution

I updated the CRD to ensure the `singular` and `plural` names match the `kind`. The corrected `names` section is:

```
spec:
  conversion:
    strategy: None
  group: instana.io
  names:
    categories:
    - monitoring
    - openshift-optional
    kind: InstanaAgent
    listKind: InstanaAgentList
    plural: instanaagents
    shortNames:
    - ia
    singular: instanaagent

```

With this change, the commands now work as expected.

```shell
kubectl get instanaagent -A
NAMESPACE       NAME            AGE
instana-agent   instana-agent   48m
```
---

## Suggestion

Please update the code in the following file:

`https://github.com/instana/instana-agent-operator/blob/main/api/v1/instanaagent_types.go#L147`

To:

`+kubebuilder:resource:path=instanaagents,singular=instanaagent,shortName=ia,scope=Namespaced,categories=monitoring;openshift-optional`
