### ISSUE TITLE
Enhancement request to support agent on masters

### ISSUE THREAD

**Issue by jferr** [instana/instana-agent-operator#40]
_Note: We are an instana customer and I have submitted this request also via instana support_

It would be a great addition to have an option in the operators crd to choose whether to install agents on masters.  Something like install_agentonmaster: True

Since the daemonset is created by and managed by the operator it seems cleaner to include this in the operator and our infrastructure as code would be much cleaner (we have the operator crd configuration yaml checked into git)

Here's my workaround...I have a jenkins job where after I apply the crd yaml I run this...so it's not a huge deal but would be a great addition.

```
cat <<EOF > dspatch.yaml
spec:
  template:
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
          operator: "Exists"
EOF

kubectl -n instana-agent patch ds instana-agent -p "$(cat dspatch.yaml)"
```
