### ISSUE TITLE
Server config not picked up from instana-agent.customresource.yaml

### ISSUE THREAD

**Issue by amitsadaphule** [instana/instana-agent-operator#60]
## SUMMARY

I was able to build and validate instana-agent-operator on ppc64le. I've also published the build-script and related validation steps (including [instana/agent image creation](https://github.com/ppc64le/build-scripts/tree/master/i/instana-agent-operator#build-instana-agent-image)) [here](https://github.com/ppc64le/build-scripts/tree/master/i/instana-agent-operator). The issue that I'm facing is, the server configuration **(endpoint, port and agent-key)** that I specify/update in the file [deploy/instana-agent.customresource.yaml](https://github.com/instana/instana-agent-operator/blob/v1.0.4/deploy/instana-agent.customresource.yaml), does not seem to be picked up/applied by the operator while bringing the agent pod up, when I load the custom resource as:

```
kubectl apply -f deploy/instana-agent.customresource.yaml
```
Instead, the server config seems to be picked up from `com.instana.agent.main.sender.Backend.cfg` file which exists in the agent tarball being used to create the agent image. I tried removing the agent key from `com.instana.agent.main.sender.Backend.cfg` while creating the image and then specifying the config parameters in the yaml file using `agent.x` tags in spec as well as using envs under `agent.env` tag as shown below.

```
apiVersion: instana.io/v1beta1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
spec:
  agent.key: <MY_AGENT_KEY>
  agent.imagePullPolicy: IfNotPresent
  agent.endpoint.host: ingress-orange-saas.instana.io # the monitoring ingress endpoint
  agent.endpoint.port: 443 # the monitoring ingress endpoint port, wrapped in quotes
  agent.env:
    INSTANA_AGENT_TAGS: example
    INSTANA_AGENT_KEY: <MY_AGENT_KEY>
    INSTANA_AGENT_ENDPOINT: ingress-orange-saas.instana.io
    INSTANA_AGENT_ENDPOINT: 443
  cluster.name: amit-minikube # replace with the name of your Kubernetes cluster
  config.files:
    configuration.yaml: |
      # You can leave this empty, or use this to configure your instana agent.
      # See https://docs.instana.io/setup_and_manage/host_agent/on/kubernetes/
```

The agent pod came up without issues, but that did not show my cluster details on the instana dashboard.

### instana-agent-operator VERSION

v1.0.4

### OS, environment

RHEL 8.2 ppc64le
java 11
maven 3.6.3

## Steps to reproduce the problem

1. Build the operator image using [this](https://github.com/ppc64le/build-scripts/blob/master/i/instana-agent-operator/instana-agent-operator_rhel8.2.sh) build-script.
2. Download the instana agent tarball for ppc64le using your instana account webUI: `More > Agents > Installing Instana Agents > (OS) Linux > (Linux) Technology > Archive (tar.gz) > Linux (64-Bit PowerPC Little Endian) > Download`
3. Extract the tarball (_instana-agent-linux-ppcle-64bit.tar.gz_) locally and remove the agent key from `etc/instana/com.instana.agent.main.sender.Backend.cfg`. Now re-pack the tarball.
4. Build the agent image as described [here](https://github.com/ppc64le/build-scripts/tree/master/i/instana-agent-operator#build-instana-agent-image).
5. Modify the file `deploy/instana-agent.customresource.yaml` in operator code to look like the one shown in summary (by replacing <MY_AGENT_KEY> with your agent key).
6. Deploy the operator and agent on minikube cluster using [these](https://github.com/ppc64le/build-scripts/tree/master/i/instana-agent-operator#validation-on-minikube) steps.
7. Both the pods come up properly. But the cluster details do not show up on the instana dashboard (webUI).

Please help me resolve this issue. Thanks!
