### ISSUE TITLE
v2.0.5 fails to install on OKD 4.10

### ISSUE THREAD

**Issue by dznaiko** [instana/instana-agent-operator#85]
Hello guys, I tried installing the latest version of the instana-agent-operator from the OpenShift Marketplace through OLM and it gets stuck in the 'Pending' state.
When I check the status there's a problem with one of the requirements:
```
oc get csv instana-agent-operator.v2.0.5 -o yaml
...
requirementStatus:
...
  - group: ""
    kind: ServiceAccount
    message: Service account does not exist
    name: controller-manager
    status: NotPresent
    version: v1
```

So basically the CSV needs a ServiceAccount that is not there. I could create it manually, but I don't think it's supposed to be like this & this is also not listed in the installation requirements.
I checked the manual from the OLM and found this [page](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/building-your-csv.md#operator-install):
```
Ensure that the serviceAccountName used in the deployment spec matches one of the Roles described under permissions.
```

However, the `permissions` section is completely missing from the instana-agent-operator CSV install spec. Could this be the problem?
